In [1]:
import pandas as pd
import os

data_path = "../data/retail_clean_dataset"

files = [
    "customer_master.csv",
    "inventory_snapshot.csv",
    "promotions.csv",
    "sales_transactions.csv",
    "sku_inventory_flags.csv",
    "sku_master.csv",
    "store_master.csv"
]

for file in files:
    path = os.path.join(data_path, file)
    
    df = pd.read_csv(path)
    
    print("=" * 60)
    print("FILE:", file)
    print("ROWS:", df.shape[0])
    print("COLUMNS:", df.shape[1])
    print("COLUMN NAMES:")
    print(df.columns.tolist())
    print()

============================================================
FILE: customer_master.csv
ROWS: 10000
COLUMNS: 7
COLUMN NAMES:
['cust_id', 'age', 'gender', 'city', 'loyalty_segment', 'preferred_channel', 'registration_date']

============================================================
FILE: inventory_snapshot.csv
ROWS: 21228
COLUMNS: 6
COLUMN NAMES:
['store_id', 'sku_id', 'stock_on_hand', 'reorder_point', 'safety_stock', 'last_restock_date']

============================================================
FILE: promotions.csv
ROWS: 100
COLUMNS: 8
COLUMN NAMES:
['promo_id', 'promo_name', 'start_date', 'end_date', 'discount_pct', 'promo_type', 'target_type', 'target_value']

============================================================
FILE: sales_transactions.csv
ROWS: 9972038
COLUMNS: 11
COLUMN NAMES:
['date', 'receipt_id', 'store_id', 'sku_id', 'customer_id', 'quantity', 'unit_price', 'total_value', 'channel', 'discount_pct', 'promo_id']

============================================================
FILE: sku_inventory_flags.csv
ROWS: 600
COLUMNS: 6
COLUMN NAMES:
['sku_id', 'flag', 'affected_stores', 'window_start', 'window_end', 'notes']

============================================================
FILE: sku_master.csv
ROWS: 5000
COLUMNS: 7
COLUMN NAMES:
['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']

============================================================
FILE: store_master.csv
ROWS: 30
COLUMNS: 5
COLUMN NAMES:
['store_id', 'store_name', 'city', 'store_type', 'opening_date']

In [2]:
sales_sample = pd.read_csv(
    "../data/retail_clean_dataset/sales_transactions.csv",
    nrows=10000
)

sales_sample.shape

(10000, 11)

In [3]:
sales_10k = pd.read_csv(
    "../data/retail_clean_dataset/sales_transactions.csv",
    nrows=10000
)

sales_10k.to_csv(
    "../data/sales_10k_raw.csv",
    index=False
)

print("Saved successfully!")
print("Shape:", sales_10k.shape)

Saved successfully!
Shape: (10000, 11)

In [4]:
sales_10k.head()

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
0,2025-04-02,RCPT00000001,ST16,SKU02498,CUST01410,1,2379.11,2379.11,In-Store,0.0,NaN
1,2025-04-02,RCPT00000001,ST16,SKU04596,CUST01410,3,335.55,1006.65,In-Store,0.0,NaN
2,2022-04-24,RCPT00000002,ST15,SKU00078,CUST00134,1,820.53,820.53,Online,0.0,NaN
3,2022-04-24,RCPT00000002,ST15,SKU00554,CUST00134,2,88.32,176.64,Online,0.0,NaN
4,2024-09-22,RCPT00000003,ST20,SKU03727,CUST08826,1,1660.93,1660.93,Online,0.0,NaN

In [5]:
sales_10k.tail()

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
9995,2025-07-23,RCPT00005205,ST21,SKU04718,CUST09510,4,148.59,594.36,Online,0.0,NaN
9996,2025-07-23,RCPT00005205,ST21,SKU00286,CUST09510,1,64.45,64.45,Online,0.0,NaN
9997,2025-07-23,RCPT00005205,ST21,SKU04596,CUST09510,1,335.55,335.55,Online,0.0,NaN
9998,2024-11-15,RCPT00005206,ST21,SKU00645,CUST06977,5,292.66,1463.30,Online,0.0,NaN
9999,2024-11-15,RCPT00005206,ST21,SKU01248,CUST06977,2,381.79,763.58,Online,0.0,NaN

In [6]:
sales_10k.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          10000 non-null  str
 1   receipt_id    10000 non-null  str
 2   store_id      10000 non-null  str
 3   sku_id        10000 non-null  str
 4   customer_id   10000 non-null  str
 5   quantity      10000 non-null  int64
 6   unit_price    10000 non-null  float64
 7   total_value   10000 non-null  float64
 8   channel       10000 non-null  str
 9   discount_pct  10000 non-null  float64
 10  promo_id      2031 non-null   str
dtypes: float64(3), int64(1), str(7)
memory usage: 1.3 MB

In [7]:
sales_10k.describe()

           quantity    unit_price   total_value  discount_pct
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       1.888200    632.648716   1118.795540      5.993360
std        1.102734    683.319010   1568.647544     13.486503
min        1.000000     24.410000     13.720000      0.000000
25%        1.000000    175.310000    241.902500      0.000000
50%        1.000000    346.490000    547.980000      0.000000
75%        3.000000    961.300000   1327.367500      0.000000
max        5.000000   4755.470000  23777.350000     49.800000

In [8]:
sales_10k.isnull().sum()

date               0
receipt_id         0
store_id           0
sku_id             0
customer_id        0
quantity           0
unit_price         0
total_value        0
channel            0
discount_pct       0
promo_id        7969
dtype: int64

In [9]:
sales_10k.duplicated().sum()

np.int64(11)

In [10]:
# Duplicate records ko inspect 

duplicates = sales_10k[sales_10k.duplicated(keep=False)]

print("Total duplicate rows:", len(duplicates))

display(duplicates.head(20))

Total duplicate rows: 22

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
270,2025-05-11,RCPT00000149,ST10,SKU02141,CUST09365,2,471.88,943.76,Online,0.0,NaN
272,2025-05-11,RCPT00000149,ST10,SKU02141,CUST09365,2,471.88,943.76,Online,0.0,NaN
314,2022-08-03,RCPT00000169,ST29,SKU04321,CUST07066,1,961.30,961.30,In-Store,0.0,NaN
315,2022-08-03,RCPT00000169,ST29,SKU04321,CUST07066,1,961.30,961.30,In-Store,0.0,NaN
544,2025-11-14,RCPT00000289,ST06,SKU04321,CUST02146,1,961.30,961.30,In-Store,0.0,NaN
545,2025-11-14,RCPT00000289,ST06,SKU04321,CUST02146,1,961.30,961.30,In-Store,0.0,NaN
2945,2024-06-22,RCPT00001531,ST25,SKU04321,CUST01969,1,961.30,744.05,Online,22.6,PROMO045
2946,2024-06-22,RCPT00001531,ST25,SKU04321,CUST01969,1,961.30,744.05,Online,22.6,PROMO045
5864,2025-10-09,RCPT00003040,ST13,SKU04321,CUST08409,1,961.30,961.30,Mobile App,0.0,NaN
5865,2025-10-09,RCPT00003040,ST13,SKU04321,CUST08409,1,961.30,961.30,Mobile App,0.0,NaN
6732,2022-07-13,RCPT00003501,ST01,SKU04596,CUST08781,1,335.55,335.55,In-Store,0.0,NaN
6733,2022-07-13,RCPT00003501,ST01,SKU04596,CUST08781,1,335.55,335.55,In-Store,0.0,NaN
7024,2023-11-10,RCPT00003644,ST17,SKU04321,CUST06381,2,961.30,1922.60,In-Store,0.0,NaN
7025,2023-11-10,RCPT00003644,ST17,SKU04321,CUST06381,2,961.30,1922.60,In-Store,0.0,NaN
8055,2022-07-06,RCPT00004185,ST01,SKU04321,CUST05629,2,961.30,1922.60,In-Store,0.0,NaN
8057,2022-07-06,RCPT00004185,ST01,SKU04321,CUST05629,2,961.30,1922.60,In-Store,0.0,NaN
9279,2022-11-13,RCPT00004820,ST01,SKU04321,CUST09043,1,961.30,961.30,Online,0.0,NaN
9280,2022-11-13,RCPT00004820,ST01,SKU04321,CUST09043,1,961.30,961.30,Online,0.0,NaN
9481,2022-01-03,RCPT00004929,ST19,SKU03119,CUST01169,1,37.56,37.56,In-Store,0.0,NaN
9482,2022-01-03,RCPT00004929,ST19,SKU03119,CUST01169,1,37.56,37.56,In-Store,0.0,NaN

In [11]:
sales_10k.columns

Index(['date', 'receipt_id', 'store_id', 'sku_id', 'customer_id', 'quantity',
       'unit_price', 'total_value', 'channel', 'discount_pct', 'promo_id'],
      dtype='str')

In [12]:
sales_10k["date"] = pd.to_datetime(sales_10k["date"])

print("Start Date:", sales_10k["date"].min())
print("End Date:", sales_10k["date"].max())

Start Date: 2022-01-01 00:00:00
End Date: 2025-12-31 00:00:00

In [13]:
sales_10k["sku_id"].nunique()

3481

In [14]:
print("Total rows:", len(sales_10k))

print("Missing promo_id:", sales_10k["promo_id"].isna().sum())

print("Non-missing promo_id:", sales_10k["promo_id"].notna().sum())

print("\nUnique promo IDs:")
print(sales_10k["promo_id"].dropna().nunique())

Total rows: 10000
Missing promo_id: 7969
Non-missing promo_id: 2031

Unique promo IDs:
72

In [15]:
# Duplicate rows remove 

print("Before removing duplicates:", len(sales_10k))

sales_10k = sales_10k.drop_duplicates().copy()

print("After removing duplicates:", len(sales_10k))
print("Duplicates removed:", 10000 - len(sales_10k))

Before removing duplicates: 10000
After removing duplicates: 9989
Duplicates removed: 11

In [16]:
numeric_columns = [
    "quantity",
    "unit_price",
    "total_value",
    "discount_pct"
]

print(sales_10k[numeric_columns].describe())

          quantity   unit_price   total_value  discount_pct
count  9989.000000  9989.000000   9989.000000   9989.000000
mean      1.888878   632.490917   1118.955129      5.997697
std       1.103053   683.597605   1569.403605     13.491571
min       1.000000    24.410000     13.720000      0.000000
25%       1.000000   175.310000    241.810000      0.000000
50%       1.000000   346.350000    547.980000      0.000000
75%       3.000000   961.300000   1327.900000      0.000000
max       5.000000  4755.470000  23777.350000     49.800000

In [17]:
for col in ["quantity", "unit_price", "total_value", "discount_pct"]:
    print(col, "negative values:", (sales_10k[col] < 0).sum())

quantity negative values: 0
unit_price negative values: 0
total_value negative values: 0
discount_pct negative values: 0

In [18]:
for col in ["quantity", "unit_price", "total_value"]:
    print(col, "zero values:", (sales_10k[col] == 0).sum())

quantity zero values: 0
unit_price zero values: 0
total_value zero values: 0

In [19]:
# Check whether total_value is calculated correctly

calculated_value = (
    sales_10k["quantity"]
    * sales_10k["unit_price"]
    * (1 - sales_10k["discount_pct"] / 100)
)

difference = (sales_10k["total_value"] - calculated_value).abs()

print("Maximum difference:", difference.max())
print("Rows with difference > 0.01:", (difference > 0.01).sum())

Maximum difference: 0.005000000000109139
Rows with difference > 0.01: 0

In [20]:
print("CHANNEL VALUES:")
print(sales_10k["channel"].value_counts())

print("\nUnique Stores:", sales_10k["store_id"].nunique())
print("Unique SKUs:", sales_10k["sku_id"].nunique())
print("Unique Customers:", sales_10k["customer_id"].nunique())
print("Unique Receipts:", sales_10k["receipt_id"].nunique())

CHANNEL VALUES:
channel
In-Store      5469
Online        3054
Mobile App    1466
Name: count, dtype: int64

Unique Stores: 30
Unique SKUs: 3481
Unique Customers: 3865
Unique Receipts: 5196

In [21]:
# Extracting a clean dataset for making 10,000 records
sales_final = pd.read_csv(
    "../data/retail_clean_dataset/sales_transactions.csv",
    nrows=10050
)

# Duplicate rows remove
sales_final = sales_final.drop_duplicates().copy()

# Date format
sales_final["date"] = pd.to_datetime(
    sales_final["date"],
    errors="coerce"
)

# Exactly 10,000 records
sales_final = sales_final.head(10000).copy()

print("Final records:", len(sales_final))
print("Final columns:", sales_final.shape[1])
print("Duplicates:", sales_final.duplicated().sum())
print("Missing values:", sales_final.isnull().sum().sum())

Final records: 10000
Final columns: 11
Duplicates: 0
Missing values: 7969

In [22]:
sales_final.to_csv(
    "../data/sales_10k_clean.csv",
    index=False
)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [23]:
import os

file_path = "../data/sales_10k_clean.csv"

print("File exists:", os.path.exists(file_path))
print("File path:", file_path)

check_df = pd.read_csv(file_path)

print("Rows:", check_df.shape[0])
print("Columns:", check_df.shape[1])
print("Duplicates:", check_df.duplicated().sum())

File exists: True
File path: ../data/sales_10k_clean.csv
Rows: 10000
Columns: 11
Duplicates: 0